# Setup
title: zard's wiki
description: Those who cannot remember the past are condemned to repeat it.
url: https://zard0214.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-admin

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

twitter:
  username: ZhechengZhao
  card: summary
logo: logo.png
social:
  name: Zhecheng Zhao
  links:
    - https://twitter.com/ZhechengZhao
    - https://github.com/zard0214
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: zard0214
  url: https://github.com/zard0214/
  email: zzhao84@sheffield.ac.uk
